<!DOCTYPE html>
<html lang="en"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="TROCKO" />
    <meta name="description" content="TROCKO">
    <!-- Document title -->
    <title>TROCKO | TERMS &amp; CONDITIONS</title>
    <!-- Stylesheets & Fonts -->
	<link rel="icon" href="images/trocko.png" type="image/png" sizes="16x16">
    <link href="http://fonts.googleapis.com/css?family=Raleway:100,300,600,700,800" rel="stylesheet" type="text/css" />
    <link href="css/plugins.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet"> 
	
	</script>
	</head>

<body class="no-page-loader">


    <!-- Wrapper -->
    <div id="wrapper">
    
		<div id="topbar" class="topbar" >
			<div class="container">
				<div class="row" >
					
					<div class="col-sm-12 no-padding">
						<div class="social-icons">
							<ul><li><a>Stay Connected:</a></li>
								<li class="social-facebook" title="Facebook"><a href="https://www.facebook.com/trockologi/" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li class="social-linkedin" title="LinkedIn "><a href="https://www.linkedin.com/company/trocko-logi-private-limited" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li class="social-linkedin" title="Instagram"><a href="https://www.instagram.com/trockologi" target="_blank"><i class="fa fa-instagram"></i></a></li>
								<li class="social-linkedin" title="Twitter"><a href="https://twitter.com/trockologi" target="_blank"><i class="fa fa-twitter"></i></a></li>
								
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
        <!-- Header -->
        <header id="header" class="header-static">
            <div id="header-wrap">
                <div class="container menubg" id="respmenu">
                    <!--Logo-->
                    <div id="logo">
                        <a href="index.php" class="logo" data-dark-logo="images/logo.svg">
                            <img src="images/logo.svg" alt="TROCKO Logo">
                        </a>
                    </div>
                    <!--End: Logo-->


                    <!--Navigation Resposnive Trigger-->
                    <div id="mainMenu-trigger">
                        <button class="lines-button x"> <span class="lines"></span> </button>
                    </div>
                    <!--end: Navigation Resposnive Trigger-->

                    <!--Navigation-->
                    <div id="mainMenu" class="light">
                        <div class="container">
                            <nav>
                                <ul id="Navigation">
                                    <li><a href="about-us.php">ABOUT US</a></li>
                                    <li><a href="services.php">SERVICES</a></li>
                                  	<li><a href="contact.php">CONTACT</a></li>
									<li><a href="driverpartners.php">DRIVER PARTNERS</a></li>
                                   <!--<li><span><a href="driverpartners.php"  class="bgblue text-white bgspace"><img src="images/driver.png" alt="driver partner"  width="22px;">DRIVER PARTNERS</a></span></li>-->
									<!--<li><a href="tel:9130190190" target="_blank" class="text-green">
										<img src="images/phone.png" alt="connect with our driver partner"   width="22px;">&nbsp;9130 190 190
										</a></li>-->
									<li><span><!--<img src="images/phone.png" alt="phone " >--><a style="background-image:url(./images/phonebg.png); background-repeat: no-repeat; background-size: cover!important;" href="tel:9130190190"  class="text-white bgspace">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;9130 190 190</a></span></li>
									<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
									
                               
                                   </ul>
                            </nav>
                        </div>
                    </div>
                    <!--end: Navigation-->
                </div>
            </div>
        </header>
        <!-- end: Header -->

        <!-- SLIDER -->
    
		<section id="slider">

			<div id="careerbanner">
		
		
		</div>

		</section>
        <!-- END SLIDER -->
		<section class="p-b-0">
            <div class="container p-r-0 p-l-0">
		<div class="col-md-12 p-r-0 p-l-0">
			 <div class="heading heading-center">
                    <h4 class="title">TERMS &amp; CONDITIONS</h4>
                </div>
			
		<h5>TROCKO TERMS OF SERVICE</h5>
		<p><strong>In terms of Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of <a href="www.trocko.in" target="_self"> </a>www.trocko.in</strong></p>
			
			<p>The domain name www.trocko.in (hereinafter referred to as "Website") is owned by Trocko Logi Private Limited, a private limited company, having its registered office at Flat No. 3, Venulaxmi Apartments, Raghuvir Society, Mukund Nagar, Pune-411037.</p>
			<p>The Terms and Conditions of use of trocko.in are to be read carefully before using or obtaining any products, services or content through our websites. Access to and use of these websites is subject to acceptance of the terms and conditions below which include our Privacy Policy. By accessing, moving past home page, using or obtaining any content, products, or services through these websites shall be taken to mean that you have read and agreed to all of the policies so binding on you and that you are contracting with us and have undertaken binding obligations with the us.</p>
			
			<p>If you do not accept all of these terms, please do not use these websites.</p>
			<p>"Trocko" or "we" or "us" means Trocko Logi Private Ltd., and its subsidiaries, affiliates, successors and assigns.</p>
			<p>"You" or "User" means any natural or legal person who has agreed to become a member on the Website by providing Registration Data while registering on the Website, or any natural or legal person who browses, accesses, or utilises the site, or any of its pages, and includes any natural or legal persons availing the services offered by Trocko through the website.</p>
			
			<ul class="p-l-15">
			  <li>&quot;Content&quot;  means the text, documents, information, data, articles, images, photographs,  graphics, software, applications, video recordings, audio recordings, sounds,  designs, features, and other materials that are available on the Site. </li>
			  <li>&quot;Content&quot;  also includes Marks and Products and Services. </li>
			  <li>&quot;Mark&quot;  means trademark, trade name, service mark, trade dress, logo, custom graphics  or icon. </li>
			  <li>&quot;Products  and Services&quot; means the unaccompanied freight booking and other related  services available through the Site. </li>
			  <li>&quot;Member&quot;  means an individual who has registered with the Site. Members choose a Member  ID and a password. </li>
			  <li>&quot;Member  ID&quot; means the email address you use (with your password) to login to our  Site. </li>
			  <li>Provider  / Vendors means Trocko, licensors, suppliers, information providers, freight  companies, packagers, and other vendors who provide their products and services  through the website. </li>
			  <li>Purchase  means to book, reserve, or purchase. The terms Site, Marks, Content and  Products and Services do not include the sites, marks, content, products or  services that are provided by third parties, or those that are available  through a link from the Site. Their use is subject to the terms set forth by  their respective owners or operations, on the third party's website. </li>
				<li>Site means the Trocko.in / www.Trocko.it website its respective sub-sites, together with the respective Content, Marks, Products and Services available from these sites and sub-sites.</li>
			</ul>
			
			<p>We hold the sole right to modify the Terms of Service without prior permission from you or informing you. The relationship creates on you a duty to periodically check the terms and stay updated on its requirements. You agree that we shall not be liable to you for any delay or other damages that might result from such modification, suspension or discontinuance. We may also at any time, change or impose fees for certain services, or establish or change general practices and limits concerning certain services. If you continue to use the website following such a change, this is deemed as consent by you to the so amended policies. As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, non-sib-licensable limited privilege to enter and use the Website.</p>
			<p>These Terms of Service are to be read in concurrence with any other agreement or contract that the user has with TrockoLogi Private Ltd.</p>
			
			<h5>ABOUT US</h5>
			<p>Trocko is a one of its kind service where we provide / facilitate last mile delivery logistics through a variety of vehicles.</p>
			<h5>HOW WE OPERATE</h5>
			<p>Once you login to our site, you shall need to select the “Source” and “Destination” locations, fill up the booking request form, enter the approximate weight, provide details of the items being moved and the date thereof, whether labour assistance may be required, and when the vehicle is required.</p>
			<h5>SCOPE AND TERMS</h5>
			<h6><strong>WEBSITE</strong></h6>
			<p>These terms govern your use of all Content, Products or Services available through the Site. You agree to be bound by these terms, and to use the Site in strict compliance with all applicable laws, rulings and regulations, and in a manner that does not negatively reflect on the goodwill or reputation of Trocko.net and its Providers.</p>
			<p>We reserve the right, in our sole discretion, to terminate the access to the website and the related services or any portion thereof at any time, without notice.</p>
			<h5>ADDITIONAL TERMS</h5>
			<p>Additional Terms may apply when you Purchase Products or Services, or when you participate in special promotions or offers. These additional terms are found in the area of the Site where you will Purchase a Product or Service, or where you will register for a special promotion.</p>
			<p>You agree to abide by the terms and conditions imposed by any Provider, including payment of all the amounts when due and comply with all rules and restrictions regarding the availability of Products or Services.</p>
			<h5>AGE RESTRICTION</h5>
			<p>Minors (as defined under the laws of their jurisdiction or residence) are not eligible to register for, use or Purchase the Products or Services available on the Site.</p>
			<h5>RESPONSIBLE PARTY</h5>
			<p>You are responsible for maintaining the secrecy of your User Name and Password. In addition, you will be financially accountable for all use of our Site by yourself and anyone using your password and login information. In the event you provide us with false and inaccurate details or we have reasonable reasons to believe you have done so, we hold the rights to permanently suspend your account.</p>
			
			
			<h5>WEBSITE AS AN INTERMEDIARY PLATFORM</h5>
			<p>The Website is a platform that Users utilize to meet and interact with one another and Vendors for their transactions.</p>
			
			<ol class="p-l-15">
			  <li>All communication which inter alia include booking, its terms, your  obligations, the vendor&rsquo;s obligations, etc are outcomes of the communication  between the vendor and You (through us). This includes, without any limitation,  the details, date, and warranties related to services after booking/reservation.  We do not have any control over such information and play no determinative role  in the finalization of the same and hence do not stand liable for the outcomes  of such communication.</li>
			  <li>Subject to the above sub-clauses, a contract exists between the Vendor  and the User and as such any breach of contract and thus, any claim arising  from such breach is the subject matter of the Vendor and the User alone and we  are in no way a party to such breach or involved in any suit arising from the  same breach. The contact/communication arising from such breach may entail  between the Vendor and the User directly without us being involved.</li>
			  <li>We act as mere facilitators who make available labour as per your  requirements. As set forth above, such contract between the User and the labour  does not include us, and we are in no way liable for any deficiency of service  that may arise which includes and is not limited to cancellation of the  reservation due to non-availability, services not meeting expectations of the User,  and poor quality.<br>
				<br>
				Disclaimer: Due&nbsp;to some technical issue, or typographical error, pricing  on any product(s) or services as is reflected on the website by vendor may be  incorrect and in such an event the vendor may cancel such reservations made by  you.</li>
			  <li>You release and indemnify us and/or any of our officers  and&nbsp;representatives from any cost, damage, liability or other consequence  of any of your actions on the Website and specifically waive any claims that  you may have in this behalf under any applicable law.</li>
			</ol>
			
			
			<h5>COMMUNICATIONS</h5>
			<p>By using this website, it is deemed that you have consented to receiving calls, autodialed and/or pre-recorded message calls, from us or our vendors, at any time, on the telephone number / contact information that has been provided by you for the use of this website. We may send booking confirmation, tracking information, cancellation, payment confirmation, refund status, schedule change or any such other information relevant for the transaction, via SMS or by voice call on the contact number given by the User at the time of booking. This includes contacting you through information received from other parties. The use of this website is also your consent to receive SMSs and phone calls from us and our vendors at any time, as we deem fit. This consent to be contacted is for purposes that include and are not limited to clarification calls and marketing and promotional calls.</p>
			<p>You  may also be contacted by Service Providers with whom we have entered into a  contract in furtherance of our rights, duties and obligations under this  document, and all other policies followed by us. The sharing of the information  provided by you is governed by the Privacy Policy.</p>
<p>You  hereby unconditionally consent that such communications via SMS and/ or voice  call is (a) upon your request and authorization, (b) &lsquo;transactional&rsquo; and not an  &lsquo;unsolicited commercial communication&rsquo; as per the guidelines of Telecom  Regulation Authority of India (TRAI) and (c) in compliance with the relevant  guidelines of TRAI or such other authority in India and abroad.</p>
<p>You  hereby agree and undertake to indemnify us against all types of losses and  damages incurred by us due to any action taken by TRAI, Access Providers (as  per TRAI regulations) or any other authority due to any erroneous compliant  raised by you against us with respect to the intimations mentioned above or due  to a wrong number or email id being provided by you for any reason whatsoever.</p>
			
			
			<h5>CHARGES</h5>
			<p>The membership of this website is free of cost and this includes the browsing of the site. We do however, charge a fee or commission for the services provided when you purchase, book or reserve vendor services through the website. Any such service fee is non-refundable. In addition, you will be responsible for all charges, fees, duties, taxes, and assessment arising out of your use of the Products and Services available from the website.</p>
			<p>In case, there is a short charging by us for any services or transaction fee or any other fee or service because of any technical or other reason, we reserve the right to deduct/charge/claim the balance amount subsequent to the transaction at our own discretion.</p>
			<p>In the rare possibilities of the reservation not getting confirmed for any reason whatsoever, we will process the refund and intimate you of the same. We shall not be under any obligation to make another booking in lieu of or to compensate/ replace the unconfirmed one. All subsequent further bookings will be treated as new transactions with no reference to the earlier unconfirmed reservation.</p>
			<p>Any refunds arising from any transactions due to any cancellation of the booking or any reason whatsoever shall be processed by us in the same bank account or debit or credit card used by the User to make the payment at the time of booking.</p>
			
			<h5>INTELLECTUAL PROPERTY AND THIRD PARTY INFORMATION</h5>
			
			<p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork belonging to vendors (collectively, "Vendor Content"), is a third party user generated content and we have no control over such third party user generated content as we are merely an intermediary for the purposes of this Terms of Service.</p>
			<p>This website is the sole and exclusive property of Trocko.in or its licensors and vendors. We retain all right, title and interest (including all copyright, trademark, patent, trade secrets, and all other intellectual property rights) in the website.</p>
			<p>Other than when provided for, the use of any content on the website, and it being reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including "mirroring") to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without Our express prior written consent is not allowed.</p>
			<p>The content that you post or provide to Trocko.in will become our property and you grant us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content you provide, and you shall not be entitled to any payment or other compensation for such use.</p>
			
			<h5>USER OBLIGATIONS</h5>
			<p>You are a restricted user of this website.</p>
			
			<ul  class="p-l-15">
  <li>You are bound not to cut, copy,  distribute, modify, recreate, reverse engineer, distribute, disseminate, post,  publish or create derivative works from, transfer, or sell any information or  software obtained from the website. With our prior permission limited use may  be allowed. For the removal of doubt, it is clarified that unlimited or  wholesale reproduction, copying of the content for commercial or non-commercial  purposes and unwarranted modification of data and information within the  content of the website is not permitted.</li>
  <li>You agree not to access (or attempt  to access) the website and/or the materials or Services on our platform&nbsp;<a href="https://blowhorn.com/">Trocko.in</a>&nbsp;/&nbsp;<a href="https://blowhorn.com/">www.Trocko.it</a>&nbsp;by any means other than through  the interface that is provided by us. The use of deep-link, robot, spider or  other automatic device, program, algorithm or methodology, or any similar or  equivalent manual process, to access, acquire, copy or monitor any portion of  the Website or content, or in any way reproduce or circumvent the navigational  structure or presentation of the Website, materials or any content, to obtain  or attempt to obtain any materials, documents or information through any means  not specifically made available through the Website is hereby expressly  prohibited. You acknowledge and agree that by accessing or using the website or  Services, You may be exposed to content from other users and vendors that you  may consider offensive, indecent or otherwise objectionable. We disclaim all  liabilities arising in relation to such allegedly offensive content on the  Website.</li>
  <li>In places where this website allows  you to post or upload data/information, You undertake to ensure that such  material is not offensive and in accordance with applicable laws. Further, You  undertake not to:</li>
  <ul  class="p-l-15">
    <li>Abuse, harass, threaten, defame any other user or vendor of the site;  disillusion, erode, abrogate, demean or otherwise violate the legal rights of  others;</li>
    <li>Engage in any activity that interferes with or disrupts access to the  Website or the Services offered through the site (or the servers and networks  which are connected to the Website);</li>
    <li>Impersonate any person or entity, or falsely state or otherwise  misrepresent your affiliation with a person or entity;</li>
    <li>Publish, post, disseminate, any information which is grossly harmful,  harassing, blasphemous, defamatory, obscene,&nbsp;pornographic, paedophilic,  libellous, invasive of another's privacy, hateful, or racially, ethnically  objectionable, disparaging, relating or encouraging money laundering or  gambling, or otherwise unlawful in any manner whatever; or unlawfully  threatening or unlawfully harassing including but not limited to indecently  representing women within the meaning of the Indecent Representation of Women  (Prohibition) Act, 1986;</li>
    <li>Post any file that infringes the Marks of other legal entities.</li>
    <li>Upload or distribute files that  contain viruses, corrupted files, or any other similar software or programs  that may damage the operation of our or our vendor websites or another's  computer;</li>
    <li>Probe, scan or test the vulnerability of the Website or any network  connected to the Website, or breach the security or authentication measures on  the Website or any network connected to the Website. You may not reverse  look-up, trace or seek to trace any information on any other user, of or visitor  to, the Website, or any other customer or vendor of the website, including any  website Account not owned by You, to its source, or exploit the Website or  Service or information made available or offered by or through the Website, in  any way whether or not the purpose is to reveal any information, including but  not limited to personal identification information, other than Your own  information, as provided for by the Website;</li>
    <li>Disrupt or interfere with the security of, or otherwise cause harm to,  the Website, systems resources, accounts, passwords, servers or networks  connected to or accessible through the Websites or any affiliated or linked  sites;</li>
    <li>Collect or store data about other  users in connection with the prohibited conduct and activities set forth in  this Section.</li>
    <li>Use the Website or any material or  Content for any purpose that is unlawful or prohibited by these Terms of Use,  or the laws of India, or to solicit the performance of any illegal activity or  other activity which infringes the rights of this website or other third  parties;</li>
    <li>Violate any code of conduct or other guidelines, which may be applicable  for or to any particular Service;</li>
    <li>Violate the Terms of Use including  but not limited to any applicable additional Terms of the Website contained  herein or elsewhere;</li>
    <li>violate any code of conduct or other guidelines, which may be applicable  for or to any particular Service;</li>
    <li>Publish, post, disseminate information that is false, inaccurate or  misleading; violate any applicable laws or regulations for the time being in  force in or outside India;</li>
    <li>Create liability for us or cause us to lose (in whole or in part) the  services of our internet service provider (&quot;ISPs&quot;) our vendors or  other suppliers;</li>
  </ul>
</ul>
	
			<h5>DISCLAIMER OF WARRANTIES AND LIABILITIES</h5>
			<h6>YOU EXPRESSLY UNDERSTAND AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</h6><br>
			<h5>THE WEBSITE, SERVICES AND OTHER MATERIALS ARE PROVIDED BY THIS WEBSITE IS ON AN "AS IS" BASIS WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WITHOUT LIMITING THE FOREGOING, THE WEBSITE MAKES NO WARRANTY THAT</h5><br>
			<ul  class="p-l-15">
			  <li>YOUR REQUIREMENTS WILL BE MET OR THAT  SERVICES PROVIDED WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE;</li>
			  <li>MATERIALS, INFORMATION OBTAINED AND  DESCRIPTIONS OF SERVICES WILL BE EFFECTIVE, ACCURATE OR RELIABLE;</li>
			  <li>ANY ERRORS OR DEFECTS IN THE WEBSITE,  SERVICES OR OTHER MATERIALS WILL BE CORRECTED.</li>
			  <li>THE SERVICES PURCHASED BY YOU AND MADE  AVAILABLE THROUGH OUR VENDORS SHALL BE AVAILABLE THROUGHOUT THE YEAR, OR  AVAILABLE AT ALL TIMES.</li>
			  <li>THE GOODS SHALL NOT BE MISPLACED OR  SHALL ARRIVE ON TIME AT THE LOCATION TO WHICH THEY ARE BEING SENT.</li>
			  <li>THE GOODS YOU SEEK TO SEND ACROSS  SHALL BE LET INTO THE TERRITORY TO WHICH THEY ARE BEING SENT, OR SHALL NOT BE  CONFISCATED BY THE GOVERNMENT AUTHORITIES AT THE POINT OF ENTRY.</li>
			</ul>
			
			<p>TO  THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE WILL HAVE NO LIABILITY  RELATED TO USER CONTENT ARISING UNDER INTELLECTUAL PROPERTY RIGHTS, LIBEL,  PRIVACY, PUBLICITY, OBSCENITY OR OTHER LAWS. THE WEBSITE ALSO DISCLAIMS ALL  LIABILITY WITH RESPECT TO THE MISUSE, LOSS, MODIFICATION OR UNAVAILABILITY OF  ANY USER CONTENT.</p>
<p>THE  USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE  OBTAINED THROUGH THE WEBSITE IS DONE ENTIRELY AT THEIR OWN DISCRETION AND RISK  AND THEY WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO THEIR COMPUTER SYSTEMS OR  LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA. THE WEBSITE  ACCEPTS NO LIABILITY FOR ANY ERRORS OR OMISSIONS, WITH RESPECT TO ANY  INFORMATION PROVIDED TO YOU WHETHER ON BEHALF OF ITSELF OR THIRD PARTIES.</p>
<p>WE  SHALL NOT BE LIABLE FOR ANY THIRD PARTY PRODUCT OR SERVICES. THE ADVERTISEMENT  AVAILABLE ON E-MAIL OR WEBSITE WITH RESPECT TO THE THIRD PARTY WEBSITE OR THE  PRODUCTS AND SERVICES ARE FOR INFORMATION PURPOSE ONLY.</p>
<p>WE  SHALL NOT BE LIABLE FOR DELAYS OR INABILITIES IN PERFORMANCE OR NON-PERFORMANCE  IN WHOLE OR IN PART OF VENDOR OBLIGATIONS DUE TO ANY CAUSES THAT ARE NOT DUE TO  ITS ACTS OR OMISSIONS AND ARE BEYOND ITS REASONABLE CONTROL, SUCH AS ACTS OF  GOD, FIRE, STRIKES, EMBARGO, ACTS OF GOVERNMENT, ACTS OF TERRORISM OR OTHER  SIMILAR CAUSES, PROBLEMS.</p>
<p>
YOU AGREE THAT THERE  CAN BE EXCEPTIONAL CIRCUMSTANCES WHERE THE SERVICE OPERATORS LIKE MAY BE UNABLE  TO HONOR THE CONFIRMED BOOKINGS DUE TO VARIOUS REASONS LIKE CLIMATIC  CONDITIONS, LABOR UNREST, INSOLVENCY, BUSINESS EXIGENCIES, GOVERNMENT  DECISIONS, OPERATIONAL AND TECHNICAL ISSUES, ROUTE ISSUES ETC.<p></p>


			<h5>INDEMNIFICATION AND LIMITATION OF LIABILITY</h5>
			<p>YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS THIS WEBSITE INCLUDING BUT NOT LIMITED TO ITS AFFILIATE VENDORS, AGENTS AND EMPLOYEES FROM AND AGAINST ANY AND ALL LOSSES, LIABILITIES, CLAIMS, DAMAGES, DEMANDS, COSTS AND EXPENSES (INCLUDING LEGAL FEES AND DISBURSEMENTS IN CONNECTION THEREWITH AND INTEREST CHARGEABLE THEREON) ASSERTED AGAINST OR INCURRED BY US THAT ARISE OUT OF, RESULT FROM, OR MAY BE PAYABLE BY VIRTUE OF, ANY BREACH OR NON-PERFORMANCE OF ANY REPRESENTATION, WARRANTY, COVENANT OR AGREEMENT MADE OR OBLIGATION TO BE PERFORMED BY YOU PURSUANT TO THESE TERMS OF USE, OR ANY OTHER ACTION INCURRED BY YOU AS A RESULT OF USING THE WEBSITE OR THE VENDOR SERVICES OFFERED THEREIN.</p>
			<p>FURTHER, YOU AGREE TO HOLD US HARMLESS AGAINST ANY CLAIMS MADE BY ANY THIRD PARTY OR ANY VENDOR DUE TO, OR ARISING OUT OF, OR IN CONNECTION WITH, YOUR USE OF THE WEBSITE, YOUR USE OF THE SERVICES OFFERED BY THE VENDOR, ANY CLAIM THAT YOUR MATERIAL CAUSED DAMAGE TO A THIRD PARTY, YOUR VIOLATION OF THE TERMS OF USE, OR YOUR VIOLATION OF ANY RIGHTS OF ANOTHER, INCLUDING ANY INTELLECTUAL PROPERTY RIGHTS.</p>

			<p>IN NO EVENT SHALL WE, OUR OFFICERS, DIRECTORS, EMPLOYEES, PARTNERS OR SUPPLIERS BE LIABLE TO YOU, THE VENDOR OR ANY THIRD PARTY FOR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL OR PUNITIVE DAMAGES WHATSOEVER, INCLUDING THOSE RESULTING FROM ANY FAILURE OR DELAY (INCLUDING WITHOUT LIMITATION THE USE OF OR INABILITY TO USE ANY COMPONENT OF THIS SITE FOR RESERVATIONS OR TICKETING), THE LOSS OF LUGGAGE OR ANY OTHER HARM INCURRED BY YOU SUCH AS LOSS OF DATA, LOSS OF EARNING ABILITIES, LOSS OF PROFITS, ANY PERFORMANCE OR NON PERFORMANCE BY US OR ANY PROVIDER, OR ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DEFECT OF MACHINERY, DELAY IN OPERATION, ETC., WHETHER OR NOT FORESEEABLE OR WHETHER OR NOT WE OR OUR VENDORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR BASED ON ANY THEORY OF LIABILITY, INCLUDING BREACH OF CONTRACT OR WARRANTY, NEGLIGENCE OR OTHER TORTIOUS ACTION, OR ANY OTHER CLAIM ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR ACCESS TO THE WEBSITE, AND THE SERVICES OR MATERIALS OFFERED ON THE WEBSITE.<</p>
				<p>SUBJECT TO APPLICABLE LAW, USE OF THIS SITE AND ITS CONTENT IS AT YOUR SOLE RISK. SERVICES AND PRODUCTS MADE AVAILABLE ON THIS SITE ARE SUBJECT TO CONDITIONS IMPOSED BY THE VENDORS, INCLUDING BUT NOT LIMITED TO TARIFFS, CONDITIONS OF CARRIAGE AND CENTRAL GOVERNMENT REGULATIONS. VENDORS WHO FURNISH PRODUCTS OR SERVICES THROUGH THE WEBSITE ARE INDEPENDENT CONTRACTORS, AND NOT OUR AGENTS OR EMPLOYEES.</p>
			<p>THE LIMITATIONS AND EXCLUSIONS IN THIS SECTION APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.</p>
			<p>IF, DESPITE THE LIMITATION ABOVE, WE OR A VENDOR IS FOUND LIABLE FOR ANY LOSS OR DAMAGE WHICH ARISES OUT OF OR IS IN ANY WAY CONNECTED WITH ANY OF THE OCCURRENCES DESCRIBED IN THE LIMITATION ABOVE, THEN WE AND THE VENDORS’ LIABILITY WILL IN NO EVENT EXCEED, IN TOTAL, THE SUM OF INR 5,000.</p>
			
			<h5>TERMINATION</h5>
			<p>Trocko.in, in its sole discretion, may, at any time and without advance notice or liability, terminate or restrict your access to all or any component of our Site, even if access continues to be allowed to others. Upon such termination or suspension, you must immediately discontinue use of the Site, and destroy any copy you have made of any portion of the Site. Accessing the Site after such termination, suspension or discontinuation shall constitute an act of trespassing. We shall not be accountable to you to such suspension or termination.</p>
			<h5>Hosting of Third Party Information</h5>
			<p>The website hosts information provided by third parties that is intended for information purposes only. We are in no way responsible to you for the accuracy, legitimacy and trueness of the information so hosted. We take reasonable care to ensure such accuracy but, you agree to not hold us liable for the falsification of any such provided information. You are responsible for evaluating the accuracy, completeness, and usefulness of any opinion, advice or other content available through the website or obtained from a linked site.</p>
			<h6><strong>Viruses</strong></h6>
			<p>We make reasonable attempts to clear the website of viruses and worms, but cannot ensure that the Site will be at all times free from viruses or other destructive software. You are urged to take appropriate safeguards before downloading any information from the Site. We accept no responsibility for any damages to computer equipment or other property which may result from use of the website or downloading anything from the website.</p>
			<h5>GENERAL</h5>
			<p>Your acceptance of these Terms, and your use of the Site do not create a joint venture, a partnership, an employment, or an agency relationship with us. You may not assign, delegate, or transfer your rights or obligations under these Terms. If we fail to act with respect to your breach or anyone else's breach on any occasion, we are not waiving our right to act with respect to future or similar breaches.</p><br>
		</div></div>
			

		</section>
       
     
			
       <!-- Footer -->
        <footer id="footer" class="footer-light">
           <div class="copyright-content">
                <div class="container no-padding">
                    <div class="col-md-6  no-padding"> <div class="copyright-text text-left">&copy; 2020 TROCKO. All Rights Reserved.</div></div>
					<div  class="col-md-6 no-padding">
						<div class="copyright-text text-right">
							<a href="terms-and-conditions.php" target="_blank">TERMS AND CONDITIONS</a> <span style="color: #50B8B1!important;">|</span> <a href="career.php">Careers</a> <span style="color: #50B8B1!important;">|</span> <a href="contact.php">Contact</a> <span style="color: #50B8B1!important;">|</span> <a href="faqs.php">FAQ<span class="text-lowercase">s</span></a>
							
						</div>
					</div>
                </div>
            </div>
        </footer>
        <!-- end: Footer -->

   
    <!-- end: Wrapper -->

 
    <a id="goToTop"><i class="fa fa-angle-up top-icon"></i><i class="fa fa-angle-up"></i></a>
	    <script src="js/jquery.min.js"></script>

    <script src="js/plugins.js"></script>
    <script src="js/functions.js"></script>
	 <script type="text/javascript">
	
			$(document).ready(function(){
				$("#data1").hide();
				$("#data2").hide();
				$("#data3").hide();
				$("#data4").hide();
				$("#data5").hide();
				
				
				$("#readmore").click(function(){
				   $("#data1").show();
				   $("#readmore").hide();
				   
					});
				 
				 $("#showless").click(function(){
				$("#data1").hide();
				   $("#readmore").show();
				    $("html, body").scrollTop(0);
					return false;
					});
				 
				 
				 /*********************************/
				 $("#readmore2").click(function(){
				   $("#data2").show();
				   $("#readmore2").hide();
					});
				 
				 $("#showless2").click(function(){
				$("#data2").hide();
				   $("#readmore2").show();
				    $("html, body").scrollTop(0);
					return false;
					});
				 /*********************************/
				 
				  $("#readmore3").click(function(){
				   $("#data3").show();
				   $("#readmore3").hide();
					});
				 
				 $("#showless3").click(function(){
				$("#data3").hide();
				   $("#readmore3").show();
				    $("html, body").scrollTop(0);
					return false;
					});
				
				
				/****************************/
				 $("#readmore4").click(function(){
				   $("#data4").show();
				   $("#readmore4").hide();
					});
				 
				 $("#showless4").click(function(){
				$("#data4").hide();
				   $("#readmore4").show();
				    $("html, body").scrollTop(0);
					return false;
					});
				
				
				/**************************/
				 $("#readmore5").click(function(){
				   $("#data5").show();
				   $("#readmore5").hide();
					});
				 
				 $("#showless5").click(function(){
				$("#data3").hide();
				   $("#readmore3").show();
				    $("html, body").scrollTop(0);
					return false;
					});
				 
			});
</script>
</body>
</html>

